nifi-master:
  ports:
  - 8080:8080/tcp
  - 9000:9000/tcp
  - 9000:9000/udp
  volumes:
  - /opt/nifi/flow:/opt/nifi/flow
  - /opt/nifi/flowfile_repository:/opt/nifi/flowfile_repository
  - /opt/nifi/content_repository:/opt/nifi/content_repository
  - /opt/nifi/database_repository:/opt/nifi/database_repository
  - /opt/nifi/provenance_repository:/opt/nifi/provenance_repository
  restart: always
  environment:
    PASSWORD: Pa22word
    ISMANAGER: 'true'
  labels:
    io.rancher.scheduler.affinity:host_label: nifi_master=true
  tty: true
  image: clemenko/nifi
  stdin_open: true
  net: host
nifi-node:
  ports:
  - 8080:8080/tcp
  - 9001:9001/tcp
  - 9001:9001/udp
  volumes:
  - /opt/nifi/flowfile_repository:/opt/nifi/flowfile_repository
  - /opt/nifi/content_repository:/opt/nifi/content_repository
  - /opt/nifi/database_repository:/opt/nifi/database_repository
  - /opt/nifi/provenance_repository:/opt/nifi/provenance_repository
  restart: always
  environment:
    PASSWORD: Pa22word
    ISNODE: 'true'
    NIFI_MASTER: ${NIFI_MASTER}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.scheduler.affinity:host_label_ne: nifi_master=true
  tty: true
  image: clemenko/nifi
  stdin_open: true
  net: host
